// <auto-generated />
using System;
using FlowerShop.Infrastructure.Persistence.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowerShop.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418165904_AddSeedDataForFlowersAndUniqueCompositeIndeksOnNameAndType")]
    partial class AddSeedDataForFlowersAndUniqueCompositeIndeksOnNameAndType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlowerShop.Domain.Entities.Categories.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Categorys_Name");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Buketi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aranžmani"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Specijalni pokloni"
                        },
                        new
                        {
                            Id = 4,
                            Name = "101 Ruža"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Saksijsko cveće"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Box mede"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Dehidrirane ruže"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Venci i suze"
                        });
                });

            modelBuilder.Entity("FlowerShop.Domain.Entities.FlowerTypes.Flower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FlowerCategory")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Color");

                    b.HasIndex("Name");

                    b.HasIndex("Name", "Color")
                        .IsUnique()
                        .HasDatabaseName("UX_Flowers_Name_Color");

                    b.HasIndex("Name", "FlowerCategory")
                        .IsUnique();

                    b.ToTable("Flowers", t =>
                        {
                            t.HasCheckConstraint("CK_Flowers_Stock_Positive", "Stock >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Red",
                            FlowerCategory = 0,
                            Name = "Ruža",
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Color = "Yellow",
                            FlowerCategory = 1,
                            Name = "Lala",
                            Stock = 150
                        },
                        new
                        {
                            Id = 3,
                            Color = "White",
                            FlowerCategory = 2,
                            Name = "Ljiljan",
                            Stock = 80
                        },
                        new
                        {
                            Id = 4,
                            Color = "Pink",
                            FlowerCategory = 0,
                            Name = "Bela rada",
                            Stock = 120
                        },
                        new
                        {
                            Id = 5,
                            Color = "Red",
                            FlowerCategory = 0,
                            Name = "Karanfil",
                            Stock = 200
                        },
                        new
                        {
                            Id = 6,
                            Color = "Orange",
                            FlowerCategory = 0,
                            Name = "Gerber",
                            Stock = 90
                        },
                        new
                        {
                            Id = 7,
                            Color = "Purple",
                            FlowerCategory = 0,
                            Name = "Orhideja",
                            Stock = 50
                        },
                        new
                        {
                            Id = 8,
                            Color = "Blue",
                            FlowerCategory = 0,
                            Name = "Iris",
                            Stock = 70
                        },
                        new
                        {
                            Id = 9,
                            Color = "Yellow",
                            FlowerCategory = 0,
                            Name = "Narcis",
                            Stock = 110
                        },
                        new
                        {
                            Id = 10,
                            Color = "Yellow",
                            FlowerCategory = 0,
                            Name = "Suncokret",
                            Stock = 60
                        },
                        new
                        {
                            Id = 11,
                            Color = "Purple",
                            FlowerCategory = 0,
                            Name = "Jorgovan",
                            Stock = 40
                        },
                        new
                        {
                            Id = 12,
                            Color = "White",
                            FlowerCategory = 0,
                            Name = "Magnolija",
                            Stock = 30
                        },
                        new
                        {
                            Id = 13,
                            Color = "Yellow",
                            FlowerCategory = 0,
                            Name = "Hrizantema",
                            Stock = 100
                        },
                        new
                        {
                            Id = 14,
                            Color = "Pink",
                            FlowerCategory = 0,
                            Name = "Božur",
                            Stock = 45
                        },
                        new
                        {
                            Id = 15,
                            Color = "White",
                            FlowerCategory = 0,
                            Name = "Jasmin",
                            Stock = 85
                        },
                        new
                        {
                            Id = 16,
                            Color = "Purple",
                            FlowerCategory = 1,
                            Name = "Lavanda",
                            Stock = 300
                        },
                        new
                        {
                            Id = 17,
                            Color = "Yellow",
                            FlowerCategory = 0,
                            Name = "Mimoza",
                            Stock = 55
                        },
                        new
                        {
                            Id = 18,
                            Color = "White",
                            FlowerCategory = 1,
                            Name = "Ruža",
                            Stock = 40
                        });
                });

            modelBuilder.Entity("FlowerShop.Domain.Entities.IdentityUser.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("FlowerShop.Domain.Entities.Ocassions.Occasion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Occasions_Name");

                    b.ToTable("Occasions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dan zaljubljenih"
                        },
                        new
                        {
                            Id = 2,
                            Name = "8. Mart - Dan žena"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rodjendan"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Svadba i venčanje"
                        });
                });

            modelBuilder.Entity("FlowerShop.Domain.Entities.ProductFlowers.ProductFlower", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("FlowerId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("ProductId", "FlowerId");

                    b.HasIndex("FlowerId");

                    b.ToTable("ProductFlowers", t =>
                        {
                            t.HasCheckConstraint("CK_ProductFlowers_Quantity_Positive", "Quantity >= 0");
                        });
                });

            modelBuilder.Entity("FlowerShop.Domain.Entities.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PromoPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Products_Name_CategoryId");

                    b.HasIndex("Price");

                    b.HasIndex("CategoryId", "Price");

                    b.ToTable("Products", t =>
                        {
                            t.HasCheckConstraint("CK_Products_Price_Positive", "Price > 0");

                            t.HasCheckConstraint("CK_Products_Stock_Positive", "Stock >= 0");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("OccasionProduct", b =>
                {
                    b.Property<int>("OccasionsId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("OccasionsId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("OccasionProduct");
                });

            modelBuilder.Entity("FlowerShop.Domain.Entities.ProductFlowers.ProductFlower", b =>
                {
                    b.HasOne("FlowerShop.Domain.Entities.FlowerTypes.Flower", "Flower")
                        .WithMany("ProductFlowers")
                        .HasForeignKey("FlowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowerShop.Domain.Entities.Products.Product", "Product")
                        .WithMany("ProductFlowers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flower");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FlowerShop.Domain.Entities.Products.Product", b =>
                {
                    b.HasOne("FlowerShop.Domain.Entities.Categories.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FlowerShop.Domain.Entities.IdentityUser.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FlowerShop.Domain.Entities.IdentityUser.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowerShop.Domain.Entities.IdentityUser.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FlowerShop.Domain.Entities.IdentityUser.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OccasionProduct", b =>
                {
                    b.HasOne("FlowerShop.Domain.Entities.Ocassions.Occasion", null)
                        .WithMany()
                        .HasForeignKey("OccasionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowerShop.Domain.Entities.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlowerShop.Domain.Entities.Categories.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("FlowerShop.Domain.Entities.FlowerTypes.Flower", b =>
                {
                    b.Navigation("ProductFlowers");
                });

            modelBuilder.Entity("FlowerShop.Domain.Entities.Products.Product", b =>
                {
                    b.Navigation("ProductFlowers");
                });
#pragma warning restore 612, 618
        }
    }
}
